version: '3'
services:

  client:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:       
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_KEY=123123123
      - MONGO_URI=mongodb://mongodb:27017/file-share
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/file-share